//
//  ConvertNinjaNamePresenter.swift
//  ninjaname
//
//  Created by Chi on 4/15/2559 BE.
//  Copyright (c) 2559 Chi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ConvertNinjaNamePresenterInput
{
  func presentSomething(response: ConvertNinjaNameResponse)
}

protocol ConvertNinjaNamePresenterOutput: class
{
  func displaySomething(viewModel: ConvertNinjaNameViewModel)
}

class ConvertNinjaNamePresenter: ConvertNinjaNamePresenterInput
{
  weak var output: ConvertNinjaNamePresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: ConvertNinjaNameResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ConvertNinjaNameViewModel()
    output.displaySomething(viewModel)
  }
}
