//
//  ConvertNinjaNameWorker.swift
//  ninjaname
//
//  Created by Chi on 4/15/2559 BE.
//  Copyright (c) 2559 Chi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ConvertNinjaNameWorker
{
  // MARK: Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
