//
//  ConvertNinjaNameInteractor.swift
//  ninjaname
//
//  Created by Chi on 4/15/2559 BE.
//  Copyright (c) 2559 Chi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ConvertNinjaNameInteractorInput
{
  func doSomething(request: ConvertNinjaNameRequest)
}

protocol ConvertNinjaNameInteractorOutput
{
  func presentSomething(response: ConvertNinjaNameResponse)
}

class ConvertNinjaNameInteractor: ConvertNinjaNameInteractorInput
{
  var output: ConvertNinjaNameInteractorOutput!
  var worker: ConvertNinjaNameWorker!
  
  // MARK: Business logic
  
  func doSomething(request: ConvertNinjaNameRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ConvertNinjaNameWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ConvertNinjaNameResponse()
    output.presentSomething(response)
  }
}
