//
//  ConvertNinjaNameConfigurator.swift
//  ninjaname
//
//  Created by Chi on 4/15/2559 BE.
//  Copyright (c) 2559 Chi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ConvertNinjaNameViewController: ConvertNinjaNamePresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension ConvertNinjaNameInteractor: ConvertNinjaNameViewControllerOutput
{
}

extension ConvertNinjaNamePresenter: ConvertNinjaNameInteractorOutput
{
}

class ConvertNinjaNameConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: ConvertNinjaNameConfigurator
  {
    struct Static {
      static var instance: ConvertNinjaNameConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = ConvertNinjaNameConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: ConvertNinjaNameViewController)
  {
    let router = ConvertNinjaNameRouter()
    router.viewController = viewController
    
    let presenter = ConvertNinjaNamePresenter()
    presenter.output = viewController
    
    let interactor = ConvertNinjaNameInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
